services:
  todoapp-postgres:
    image: postgres:18.1-bookworm
    container_name: todoapp-env-postgres
    environment:
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: 123
    volumes:
      - ./out/pgdata/var/lib/postgresql:/var/lib/postgresql/data
    restart: always

    
